name: build-pull-request

on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cit-resewn-${{ steps.ref.outputs.branch }}
          path: build/libs/*.jar
